###multistage build

## Stage 1. build the react app
FROM node:20-alpine AS builder

WORKDIR /opt/web
COPY package.json package-lock.json ./
RUN npm install
ENV PATH="./node_modules/.bin:$PATH"
COPY . ./
COPY .env.development .env
RUN npm run build

## Stage 2. build the production (server) environment
FROM nginx:1.17-alpine

# Install curl and envsubst
RUN apk --no-cache add curl
RUN apk --no-cache add bash
RUN curl -L https://github.com/a8m/envsubst/releases/download/v1.1.0/envsubst-`uname -s`-`uname -m` -o envsubst && \
    chmod +x envsubst && \
    mv envsubst /usr/local/bin

# Copy config file over to the template
COPY ./nginx.config /etc/nginx/nginx.template

# Set working directory to nginx folder
WORKDIR /usr/share/nginx/html

# Substitute out default.conf file with nginx.template AND start the nginx server
CMD ["/bin/sh", "-c", "envsubst < /etc/nginx/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]

# Generate react Static Build files for nginx to use
COPY --from=builder /opt/web/build /usr/share/nginx/html


 
