# Build the react app
FROM node:20-alpine AS builder

WORKDIR /opt/web

COPY package.json package-lock.json ./
RUN npm install

ENV PATH="./node_modules/.bin:$PATH"
COPY . ./
COPY .env.development .env.production
RUN npm run build
 