version: "3"
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_API_URL: http://localhost:5000
      NODE_ENV: development
    volumes:
      - ./:/usr/src/project
    ports:
      - 3000:3000
    stdin_open: true
