FROM node:14.1-alpine

RUN userdel node

ARG UID=1000
RUN useradd --uid $UID --create-home user
USER user

WORKDIR /usr/src/project/app/

ENV PATH="/usr/src/project/app/node_modules/.bin:${PATH}"

CMD ["npm", "start"]
