// Configure constants for any routes here. When you need to refer to a routes import the routes constant into the file.
const ROUTES_CONFIG = {
  ROUTE_HOME: '/',
  ROUTE_QUIZHOME: '/start',
  ROUTE_QUIZ: '/questionnaire',
  ROUTE_SUBMIT_SET_TWO: '/submit-set-two',
  ROUTE_PERSONALITY: '/start',
  ROUTE_SUBMIT: '/submit',
  ROUTE_LOCATION: '/set-location',
  ROUTE_MYTHS: '/myths',
  ROUTE_SOLUTIONS: '/solutions',
  ROUTE_CONVERSATIONS: '/conversations',
  ROUTE_VALUES: '/personal-values',
  ROUTE_PRIVACY: '/privacy',
  ROUTE_FEED: '/climate-feed',
  ROUTE_REGISTER: '/sign-up',
  ROUTE_LOGIN: '/login',
  ROUTE_PASSWORD_RESET: '/password-reset',
  ROUTE_SHARE_LINK: '/sharelink',
  ROUTE_LANDING: '/landing/:conversationId',
  ROUTE_HOW_CM_WORKS: '/how-cm-works',
  PROFILE_MENU: '/profile-menu',
  USERB_CORE_VALUES: '/core-values',
  USERB_SHARED_VALUES: '/shared-values-user-b',
  USERB_SHARED_IMPACTS: '/shared-impacts',
  USERB_SHARED_SOLUTIONS: '/shared-solutions',
  USERB_SHARED_SUMMARY: '/shared-summary',
  USERB_ROUTE_REGISTER: '/sign-up-user-b',
  USERB_SHARED_SUCCESS: '/shared',
  SHARED_VALUES: '/shared-values',
  USERA_SHARED_FEED: '/user-a-shared-feed',
  USERB_NO_CONSENT: '/user-b/no-share',
};

export default ROUTES_CONFIG;
